server:
  port: 19093

spring:
  datasource:
    url: jdbc:mysql://localhost:13306/msa
    username: msa
    password: 11301300
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update